"""
AI meeting notes (Transync-style): title, short summary, decisions and action items for a saved
transcript, generated by OpenAI after the call when an OpenAI key is set.
"""
import json
import os

from python_socks import ProxyError

from voice_clone import CloneError, https_request

API_URL = os.environ.get("LIVE_TRANSLATOR_OPENAI_API", "https://api.openai.com/v1/responses")
MODEL = "gpt-6-luna"  # OpenAI's cost-efficient model (docs, Sep 2026)
MAX_CHARS = 60_000    # keep the request small; the end of long calls matters most

SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["title", "summary", "decisions", "action_items"],
    "properties": {
        "title": {"type": "string", "description": "3-8 words"},
        "summary": {"type": "string", "description": "3-6 sentences"},
        "decisions": {"type": "array", "items": {"type": "string"}},
        "action_items": {"type": "array", "items": {"type": "string"}},
    },
}

INSTRUCTIONS = (
    "You write meeting notes for a bilingual call transcript. 'Я' is the user, 'Собеседник' is the other "
    "person; lines starting with '→' are machine translations of the line above. Write everything in Russian. "
    "title: what the call was about in 3-8 words. summary: the key points in 3-6 sentences. decisions: what "
    "was agreed. action_items: concrete next steps with who does them when stated. Empty lists are fine; "
    "never invent facts that are not in the transcript."
)


def summarize(api_key, transcript, proxy):
    """Return {title, summary, decisions, action_items} for a transcript."""
    if len(transcript) > MAX_CHARS:
        transcript = "…\n" + transcript[-MAX_CHARS:]
    body = json.dumps({
        "model": MODEL,
        "instructions": INSTRUCTIONS,
        "input": transcript,
        "text": {"format": {"type": "json_schema", "name": "meeting_notes", "schema": SCHEMA, "strict": True}},
    }).encode()
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    try:
        status, data = https_request("POST", API_URL, headers, body, proxy)
    except (OSError, ProxyError) as e:
        raise CloneError(f"Нет связи с OpenAI ({e}). Включи VPN.") from e
    if status in (401, 403):
        raise CloneError("OpenAI отклонил ключ (или регион заблокирован — включи VPN).")
    if status != 200:
        raise CloneError(f"OpenAI: HTTP {status} {data[:300].decode('utf-8', 'replace')}")
    response = json.loads(data)
    for item in response.get("output", ()):
        for part in item.get("content", ()) or ():
            if part.get("type") == "output_text":
                return json.loads(part["text"])
    raise CloneError("OpenAI вернул пустой ответ.")


def to_markdown(notes, transcript, header):
    lines = [f"# {notes.get('title') or header}", "", header, ""]
    if notes.get("summary"):
        lines += ["## Кратко", "", notes["summary"], ""]
    for key, title in (("decisions", "Решения"), ("action_items", "Задачи")):
        if notes.get(key):
            lines += [f"## {title}", ""] + [f"- {item}" for item in notes[key]] + [""]
    lines += ["## Стенограмма", "", "```", transcript.strip(), "```", ""]
    return "\n".join(lines)
